version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0 # Use the appropriate version of .NET Core SDK
    commands:
      - echo "Installing dependencies..."
      - cd src/YourAspNetCoreApp # Change this to your app's directory
      - dotnet restore

  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      # You can add any pre-build tasks here

  build:
    commands:
      - echo "Building ASP.NET Core app..."
      - dotnet build --configuration Release
      # You might need additional build steps like webpack or asset pre-processing

  post_build:
    commands:
      - echo "Running post-build tasks..."
      # You can add any post-build tasks here

artifacts:
  files:
    - 'src/YourAspNetCoreApp/bin/Release/net5.0/publish/**/*' # Change this path according to your publish output
  base-directory: src/YourAspNetCoreApp # Change this to your app's directory
