name: .NET Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: publish
        run: dotnet publish -c Release --output ./Release

      - name: Zip folder
        run: |
          zip -r Release.zip ./Release
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v1.0.18 # Change this to the desired tag/version
          release_name: Release 1.0.18 # Change this to the desired release name
          body: |
            Describe the changes and updates in this release.
          draft: false
          prerelease: false
          
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.18
          files: "Release.zip"
        env:
          GITHUB_TOKEN: ${{ github.token }}
    



     
     
