name: .NET Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: Build and Publish
        run: dotnet publish -c Release -o ./Release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v2.0.18
          release_name: Release v2.0.18
          body: |
            Release for ${{ github.ref }}
            Published on: $(date +'%Y-%m-%d %H:%M:%S')
          draft: false
          prerelease: false
          
      - name: working dir
        run: echo '${{ github.workspace }}'
      - name: Zip folder
        run: |
          zip -r Release.zip ./Release
          
      - name : list Dir
        run: ls

        
      
